name: Vulnerability scan

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:


jobs:
  vulnerability-scan:
    name: Vulnerability scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Vulnerability scan
        env:
          SBOM_CHECK_LOCAL_DB: ${{ vars.SBOM_CHECK_LOCAL_DB }}
          SBOM_MATTERMOST_WEBHOOK: ${{ secrets.SBOM_MATTERMOST_WEBHOOK }}
          NVDAPIKEY: ${{ secrets.NVDAPIKEY }}
        uses: espressif/esp-idf-sbom-action@master
